// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Cards;

/// <summary>Requires 4 Faith in Tyr. For {AvengingWrathPower} turns, your Attacks deal 5 additional damage.</summary>
public sealed class AvengingWrath() : PaladinCard(2, CardType.Skill, CardRarity.Rare, TargetType.Self)
{
    // Requires 4 Faith in Tyr. Outside combat the card reads as playable, like the base class.
    protected override bool IsPlayable => Owner?.PlayerCombatState == null || FaithTracks.Has(Owner, Deity.Tyr, 4);
    protected override IEnumerable<DynamicVar> CanonicalVars => [new PowerVar<AvengingWrathPower>(3m)];
    protected override IEnumerable<IHoverTip> ExtraHoverTips => [HoverTipFactory.FromPower<AvengingWrathPower>()];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CreatureCmd.TriggerAnim(Owner.Creature, "PowerUp", Owner.Character.PowerUpAnimDelay);
        await PowerCmd.Apply<AvengingWrathPower>(choiceContext, Owner.Creature, DynamicVars["AvengingWrathPower"].BaseValue, Owner.Creature, this);
    }

    protected override void OnUpgrade() { DynamicVars["AvengingWrathPower"].UpgradeValueBy(2m); }

    private IEnumerable<Creature> Allies()  => Owner.Creature.CombatState.PlayerCreatures.OfType<Creature>().Where(c => c.IsAlive);
    private IEnumerable<Creature> Enemies() => Owner.Creature.CombatState.Creatures.OfType<Creature>().Where(c => !c.IsPlayer && c.IsHittable);
}
