// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Cards;

/// <summary>Gain 1 Faith in your highest deity.</summary>
public sealed class Devotion() : PaladinCard(1, CardType.Skill, CardRarity.Uncommon, TargetType.Self)
{
    protected override IEnumerable<DynamicVar> CanonicalVars => [];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CreatureCmd.TriggerAnim(Owner.Creature, "Cast", Owner.Character.CastAnimDelay);
        FaithTracks.Gain(Owner, FaithTracks.Highest(Owner).deity, 1);
    }

    protected override void OnUpgrade() { EnergyCost.UpgradeBy(-1); }

    private IEnumerable<Creature> Allies()  => Owner.Creature.CombatState.PlayerCreatures.OfType<Creature>().Where(c => c.IsAlive);
    private IEnumerable<Creature> Enemies() => Owner.Creature.CombatState.Creatures.OfType<Creature>().Where(c => !c.IsPlayer && c.IsHittable);
}
