// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Cards;

/// <summary>Requires 3 Faith in Torm. Gain {Warded} Warded.</summary>
public sealed class ImmovableObject() : PaladinCard(2, CardType.Skill, CardRarity.Uncommon, TargetType.Self)
{
    public override bool GainsBlock => true;
    // Requires 3 Faith in Torm. Outside combat the card reads as playable, like the base class.
    protected override bool IsPlayable => Owner?.PlayerCombatState == null || FaithTracks.Has(Owner, Deity.Torm, 3);
    protected override IEnumerable<DynamicVar> CanonicalVars => [new DynamicVar("Warded", 15m)];
    protected override IEnumerable<IHoverTip> ExtraHoverTips => [HoverTipFactory.FromPower<WardedPower>()];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CreatureCmd.GainBlock(Owner.Creature, DynamicVars["Warded"].BaseValue, ValueProp.Move, cardPlay);
        await PowerCmd.Apply<WardedPower>(choiceContext, Owner.Creature, DynamicVars["Warded"].BaseValue, Owner.Creature, this);
    }

    protected override void OnUpgrade() { DynamicVars["Warded"].UpgradeValueBy(5m); }

    private IEnumerable<Creature> Allies()  => Owner.Creature.CombatState.PlayerCreatures.OfType<Creature>().Where(c => c.IsAlive);
    private IEnumerable<Creature> Enemies() => Owner.Creature.CombatState.Creatures.OfType<Creature>().Where(c => !c.IsPlayer && c.IsHittable);
}
