// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Cards;

/// <summary>Requires 3 Faith in Ilmater. Spend 3 Faith in Ilmater. Heal a player {Heal} HP.</summary>
public sealed class WordOfGlory() : PaladinCard(1, CardType.Skill, CardRarity.Rare, TargetType.AnyPlayer)
{
    // Requires 3 Faith in Ilmater. Outside combat the card reads as playable, like the base class.
    protected override bool IsPlayable => Owner?.PlayerCombatState == null || FaithTracks.Has(Owner, Deity.Ilmater, 3);
    protected override IEnumerable<DynamicVar> CanonicalVars => [new HealVar(12m)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (FaithTracks.Spend(Owner, Deity.Ilmater, 3) > 0) { await CreatureCmd.TriggerAnim(Owner.Creature, "Cast", Owner.Character.CastAnimDelay); await CreatureCmd.Heal(cardPlay.Target!, DynamicVars.Heal.BaseValue); }
    }

    protected override void OnUpgrade() { DynamicVars["Heal"].UpgradeValueBy(4m); }

    private IEnumerable<Creature> Allies()  => Owner.Creature.CombatState.PlayerCreatures.OfType<Creature>().Where(c => c.IsAlive);
    private IEnumerable<Creature> Enemies() => Owner.Creature.CombatState.Creatures.OfType<Creature>().Where(c => !c.IsPlayer && c.IsHittable);
}
