// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;

/// <summary>The first time you would die this combat, instead heal to a third of your Max HP.</summary>
public sealed class ArdentDefenderPower : PaladinPower
{
    public override PowerType Type => PowerType.Buff;
    public override PowerStackType StackType => PowerStackType.Single;

    private bool _used;
    public override bool ShouldDie(Creature creature)
    {
        if (creature != Owner || _used) return true;
        _used = true;
        Flash();
        _ = CreatureCmd.SetCurrentHp(Owner, Math.Max(1, Owner.MaxHp / 3));
        _ = PowerCmd.Remove(this);
        return false;
    }
}
