// <auto-generated> tools/gen_paladin.py -- edit the spec, not this file. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloSpire.HelloSpireCode.Characters.PaladinContent.Faith;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;

namespace HelloSpire.HelloSpireCode.Characters.PaladinContent.Powers;

/// <summary>Whenever an ally is healed, every other ally heals 1 HP.</summary>
public sealed class AuraOfMercyPower : PaladinPower
{
    public override PowerType Type => PowerType.Buff;
    public override PowerStackType StackType => PowerStackType.Counter;

    private bool _busy;
    public override async Task AfterCurrentHpChanged(Creature creature, decimal delta)
    {
        if (_busy || delta <= 0m || !creature.IsPlayer || creature == Owner) return;
        _busy = true;
        try { foreach (var ally in CombatState.PlayerCreatures.OfType<Creature>().Where(c => c.IsAlive).Where(c => c != creature)) await CreatureCmd.Heal(ally, Amount); }
        finally { _busy = false; }
    }
}
